INSERT INTO DEPARTMENT (ID, DESCRIPTION, NAME) VALUES (1,'HUMAN RESOURCES','HR');
INSERT INTO DEPARTMENT (ID, DESCRIPTION, NAME) VALUES (2,'AGILE COACH','AGILE');
INSERT INTO DEPARTMENT (ID, DESCRIPTION, NAME) VALUES (3,'INFORMATION TECHNOLOGY','IT');

INSERT INTO EMPLOYER (ID, FULL_NAME, DEPARTMENT_ID) VALUES (1,'JOHN',1);
INSERT INTO EMPLOYER (ID, FULL_NAME, DEPARTMENT_ID) VALUES (2,'JACK',2);
INSERT INTO EMPLOYER (ID, FULL_NAME, DEPARTMENT_ID) VALUES (3,'PHILLIP',3);