INSERT INTO DEPARTMENT (ID, DESCRIPTION, NAME) VALUES (1,'HUMAN RESOURCES','HR');
INSERT INTO DEPARTMENT (ID, DESCRIPTION, NAME) VALUES (2,'AGILE COACH','AGILE');
INSERT INTO DEPARTMENT (ID, DESCRIPTION, NAME) VALUES (3,'INFORMATION TECHNOLOGY','IT');

INSERT INTO EMPLOYER (ID, FULL_NAME, DEPARTMENT_ID, ACTIVE) VALUES (1,'JOHN',1,true);
INSERT INTO EMPLOYER (ID, FULL_NAME, DEPARTMENT_ID, ACTIVE) VALUES (2,'JACK',2,true);
INSERT INTO EMPLOYER (ID, FULL_NAME, DEPARTMENT_ID, ACTIVE) VALUES (3,'PHILLIP',3,true);